name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "Regex"
path = "../"

[[require]]
name = "UnicodeBasic"
git = "https://github.com/fgdorais/lean4-unicode-basic.git"
rev = "main"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.26.0"
